<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Bhargav" failures="1" tests="3" name="Test" time="0.12" errors="0" timestamp="2023-10-14T15:16:50 IST">
  <testcase classname="testngPack.ListenersTest" name="m2" time="0.028">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testngPack.ListenersTest.m2(ListenersTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- m2 -->
  <testcase classname="testngPack.ListenersTest" name="m1" time="0.001"/>
  <testcase classname="testngPack.ListenersTest" name="m3" time="0.0">
    <skipped/>
  </testcase> <!-- m3 -->
</testsuite> <!-- Test -->
